-- AlterTable
ALTER TABLE "Owner" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "contactNumber" DROP NOT NULL,
ALTER COLUMN "adharNumber" DROP NOT NULL,
ALTER COLUMN "adharImage" DROP NOT NULL,
ALTER COLUMN "numberOfProperties" DROP NOT NULL,
ALTER COLUMN "totalRevenue" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Tenant" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "contactNumber" DROP NOT NULL,
ALTER COLUMN "contactNumber" SET DATA TYPE BIGINT,
ALTER COLUMN "adharNumber" DROP NOT NULL,
ALTER COLUMN "adharNumber" SET DATA TYPE BIGINT,
ALTER COLUMN "adharImage" DROP NOT NULL,
ALTER COLUMN "workingArea" DROP NOT NULL,
ALTER COLUMN "rentAmount" DROP NOT NULL,
ALTER COLUMN "rentedPropertyId" DROP NOT NULL;
